#Requires -Modules Pester
BeforeAll {
    . "$PSScriptRoot/../scripts/env_utils.ps1"
    . "$PSScriptRoot/../scripts/wsl_config.ps1"
    . "$PSScriptRoot/../scripts/docker_helpers.ps1"
    . "$PSScriptRoot/../scripts/resource_settings.ps1"
    function Write-AppLog { param($Message, $Level) }
}
Describe 'Container resource planning and persistence' {
    BeforeEach {
        $script:wsl = Join-Path $TestDrive '.wslconfig'
        $script:envFile = Join-Path $TestDrive '.env'
        Remove-Item $script:wsl, $script:envFile -Force -ErrorAction SilentlyContinue
    }
    It 'Matches both limits to each selected profile' -TestCases @(
        @{ Profile = 'light'; GB = 3; Cpu = 2 },
        @{ Profile = 'standard'; GB = 6; Cpu = 4 },
        @{ Profile = 'heavy'; GB = 12; Cpu = 6 }
    ) {
        param($Profile, $GB, $Cpu)
        $plan = Get-ContainerResourcePlan $Profile 32 16 $script:wsl $script:envFile
        $plan.MemoryBytes | Should -Be ($GB * 1GB)
        $plan.CpuCount | Should -Be $Cpu
    }
    It 'Keeps existing custom WSL memory and CPU settings on an upgrade' {
        "# WSL Configuration - Auto-generated by AI CLI Docker Setup`n# Profile: HEAVY`n[wsl2]`nmemory=14GB`nprocessors=6" | Set-Content $script:wsl
        $plan = Get-ContainerResourcePlan keep 32 16 $script:wsl $script:envFile
        $plan.MemoryBytes | Should -Be 14GB
        $plan.CpuCount | Should -Be 6
    }
    It 'Still honours WSL settings when the user skips rewriting that file' {
        "[wsl2]`nmemory=3072MB`nprocessors=3" | Set-Content $script:wsl
        $plan = Get-ContainerResourcePlan skip 32 16 $script:wsl $script:envFile
        $plan.MemoryBytes | Should -Be 3GB
        $plan.CpuCount | Should -Be 3
    }
    It 'Uses the WSL half-host-RAM default when memory is unset' {
        (Get-ContainerResourcePlan skip 32 16 $script:wsl $script:envFile).MemoryBytes | Should -Be 16GB
    }
    It 'Preserves resource button choices through later setup with existing WSL settings' {
        "[wsl2]`nmemory=12GB`nprocessors=6" | Set-Content $script:wsl
        Save-ContainerResourceSettings $script:envFile 8GB 4 $true
        $plan = Get-ContainerResourcePlan keep 32 16 $script:wsl $script:envFile
        $plan.MemoryBytes | Should -Be 8GB
        $plan.CpuCount | Should -Be 4
        $plan.Custom | Should -Be $true
    }
    It 'Uses a newly chosen profile instead of older custom settings' {
        Save-ContainerResourceSettings $script:envFile 8GB 4 $true
        $plan = Get-ContainerResourcePlan light 32 16 $script:wsl $script:envFile
        $plan.MemoryBytes | Should -Be 3GB
        $plan.Custom | Should -Be $false
    }
    It 'Stops when an existing WSL file could not be read' {
        'unreadable' | Set-Content $script:wsl
        Mock Parse-WSLConfig { @{ Exists = $false } }
        { Get-ContainerResourcePlan keep 32 16 $script:wsl $script:envFile } | Should -Throw '*could not be read*'
    }
    It 'Rejects malformed memory settings instead of silently falling back to 4 GB' {
        "[wsl2]`nmemory=invalid" | Set-Content $script:wsl
        { Get-ContainerResourcePlan keep 32 16 $script:wsl $script:envFile } | Should -Throw
    }
    It 'Rejects saved resource limits above a reduced WSL budget' {
        "[wsl2]`nmemory=6GB`nprocessors=4" | Set-Content $script:wsl
        Save-ContainerResourceSettings $script:envFile 8GB 4 $true
        { Get-ContainerResourcePlan keep 32 16 $script:wsl $script:envFile } | Should -Throw '*exceed*'
    }
    It 'Preserves other settings and replaces duplicate resource entries in one atomic write' {
        "# user configuration`nWORKSPACE_PATH=C:\AI_Work`nAI_DOCKER_MEMORY_LIMIT=4G`nAI_DOCKER_MEMORY_LIMIT=5G`nAI_DOCKER_CPU_LIMIT=2" | Set-Content $script:envFile
        Save-ContainerResourceSettings $script:envFile 10GB 6 $true
        $content = Get-Content $script:envFile -Raw
        $content | Should -Match 'WORKSPACE_PATH=C:\\AI_Work'
        $content | Should -Match '# user configuration'
        ([regex]::Matches($content, 'AI_DOCKER_MEMORY_LIMIT=')).Count | Should -Be 1
        (Read-EnvFile $script:envFile)['AI_DOCKER_MEMORY_LIMIT'] | Should -Be '10737418240'
        (Read-EnvFile $script:envFile)['AI_DOCKER_CUSTOM_RESOURCES'] | Should -Be '1'
    }
    It 'Stops when the settings cannot be saved' {
        Mock Write-EnvFileAtomic { $false }
        { Save-ContainerResourceSettings $script:envFile 10GB 6 } | Should -Throw '*Could not save*'
    }
}
Describe 'Live container resource changes' {
    BeforeEach {
        $script:envFile = Join-Path $TestDrive 'runtime.env'
        Remove-Item $script:envFile -Force -ErrorAction SilentlyContinue
        $script:state = @{ Memory = 4GB; MemorySwap = 8GB; NanoCpus = 6000000000 }
        $script:updateFails = $false
        $script:verificationFails = $false
        $script:updateCount = 0
        Mock Invoke-DockerCommand {
            param($DockerPath, $Arguments)
            if ($Arguments[0] -eq 'update') {
                $script:updateCount++
                if ($script:updateFails -and $script:updateCount -eq 1) { return @{ Success = $false; Error = 'daemon error' } }
                $script:state.Memory = [long]$Arguments[2]
                $script:state.MemorySwap = [long]$Arguments[4]
                $script:state.NanoCpus = [long]([double]$Arguments[6] * 1e9)
                return @{ Success = $true; Output = 'ai-cli' }
            }
            if ($script:verificationFails -and $script:updateCount -eq 1) { return @{ Success = $false; Error = 'timeout' } }
            return @{ Success = $true; Output = ($script:state | ConvertTo-Json -Compress) }
        }
    }
    It 'Applies and verifies limits without any build, stop, restart or recreate' {
        Set-RunningContainerResources docker $script:envFile 10GB 4 12GB 6
        $script:state.Memory | Should -Be 10GB
        $script:state.MemorySwap | Should -Be 14GB
        $script:state.NanoCpus | Should -Be 4000000000
        (Read-EnvFile $script:envFile)['AI_DOCKER_MEMORY_LIMIT'] | Should -Be '10737418240'
        Should -Invoke Invoke-DockerCommand -Times 3 -Exactly
        Should -Invoke Invoke-DockerCommand -Times 0 -ParameterFilter { $Arguments[0] -notin @('update', 'inspect') }
    }
    It 'Preserves unlimited swap' {
        $script:state.MemorySwap = -1
        Set-RunningContainerResources docker $script:envFile 10GB 4 12GB 6
        $script:state.MemorySwap | Should -Be -1
    }
    It 'Rejects requests above the current VM budget before touching Docker' {
        { Set-RunningContainerResources docker $script:envFile 14GB 4 12GB 6 } | Should -Throw
        Should -Invoke Invoke-DockerCommand -Times 0
    }
    It 'Rejects requests above the current CPU budget' {
        { Set-RunningContainerResources docker $script:envFile 10GB 8 12GB 6 } | Should -Throw
        Should -Invoke Invoke-DockerCommand -Times 0
    }
    It 'Leaves saved settings unchanged when Docker rejects the update' {
        $script:updateFails = $true
        { Set-RunningContainerResources docker $script:envFile 10GB 4 12GB 6 } | Should -Throw '*restored*'
        Test-Path $script:envFile | Should -Be $false
        $script:state.Memory | Should -Be 4GB
    }
    It 'Restores runtime limits when verification fails' {
        $script:verificationFails = $true
        { Set-RunningContainerResources docker $script:envFile 10GB 4 12GB 6 } | Should -Throw '*restored*'
        $script:state.Memory | Should -Be 4GB
        Test-Path $script:envFile | Should -Be $false
    }
    It 'Restores runtime limits when saving fails' {
        Mock Write-EnvFileAtomic { $false }
        { Set-RunningContainerResources docker $script:envFile 10GB 4 12GB 6 } | Should -Throw '*restored*'
        $script:state.Memory | Should -Be 4GB
        $script:state.NanoCpus | Should -Be 6000000000
    }
    It 'Does not claim rollback succeeded if the restored limits cannot be read' {
        Mock Write-EnvFileAtomic { $false }
        Mock Invoke-DockerCommand {
            param($DockerPath, $Arguments)
            if ($Arguments[0] -eq 'update') { $script:updateCount++; return @{ Success = $true } }
            if ($script:updateCount -eq 0) { return @{ Success = $true; Output = '{"Memory":4294967296,"MemorySwap":8589934592,"NanoCpus":6000000000}' } }
            if ($script:updateCount -eq 1) { return @{ Success = $true; Output = '{"Memory":10737418240,"MemorySwap":15032385536,"NanoCpus":4000000000}' } }
            return @{ Success = $false; Error = 'timeout' }
        }
        { Set-RunningContainerResources docker $script:envFile 10GB 4 12GB 6 } | Should -Throw '*Could not restore*'
    }
    It 'Does not update a container that cannot be inspected' {
        Mock Invoke-DockerCommand { @{ Success = $false; Error = 'timeout' } }
        { Set-RunningContainerResources docker $script:envFile 10GB 4 12GB 6 } | Should -Throw '*inspect*'
        Should -Invoke Invoke-DockerCommand -Times 1
    }
}
