#!/usr/bin/env bash
# setup_mobile_access.sh - Configure SSH, Mosh, and tmux for mobile access
# Only runs when ENABLE_MOBILE_ACCESS=1

# Source logging library (if available)
if [ -f "/usr/local/lib/logging.sh" ]; then
    source "/usr/local/lib/logging.sh"
    LOG_FILE=$(init_logging "MOBILE_ACCESS" "mobile_access")
fi

# Helper function for logging
mobile_log() {
    local level="$1"
    local message="$2"
    if [ -n "${LOG_FILE:-}" ]; then
        log_message "MOBILE_ACCESS" "$level" "$message" "$LOG_FILE"
    else
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] [$level] [MOBILE_ACCESS] $message"
    fi
}

# Get username from argument or environment
USER_NAME="${1:-${USER_NAME:-}}"
if [ -z "$USER_NAME" ]; then
    mobile_log "ERROR" "USER_NAME not provided"
    exit 1
fi

# Check if mobile access is enabled
if [ "${ENABLE_MOBILE_ACCESS:-0}" != "1" ]; then
    mobile_log "DEBUG" "Mobile access not enabled (ENABLE_MOBILE_ACCESS != 1), skipping setup"
    exit 0
fi

mobile_log "INFO" "Setting up mobile access (SSH + Mosh + tmux) for user: $USER_NAME"

# Get configuration from environment with defaults
SSH_PORT="${SSH_PORT:-2222}"
MOSH_PORT_START="${MOSH_PORT_START:-60001}"
MOSH_PORT_END="${MOSH_PORT_END:-60005}"

mobile_log "INFO" "SSH port: $SSH_PORT, Mosh ports: $MOSH_PORT_START-$MOSH_PORT_END"

# Create SSH directories with correct permissions
USER_HOME="/home/$USER_NAME"
SSH_DIR="$USER_HOME/.ssh"

mobile_log "INFO" "Creating SSH directory structure..."
mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"
chown "$USER_NAME:$USER_NAME" "$SSH_DIR"

# Create authorized_keys file if it doesn't exist
if [ ! -f "$SSH_DIR/authorized_keys" ]; then
    touch "$SSH_DIR/authorized_keys"
    chmod 600 "$SSH_DIR/authorized_keys"
    chown "$USER_NAME:$USER_NAME" "$SSH_DIR/authorized_keys"
    mobile_log "INFO" "Created empty authorized_keys file"
else
    mobile_log "INFO" "authorized_keys file already exists"
fi

# Create sshd run directory
mkdir -p /run/sshd

# Write secure sshd configuration
mobile_log "INFO" "Configuring SSH daemon..."
cat > /etc/ssh/sshd_config << EOF
# AI Docker CLI - Mobile Access SSH Configuration
# Generated by setup_mobile_access.sh

# Network settings
Port $SSH_PORT
ListenAddress 0.0.0.0
Protocol 2

# Authentication - keys only, no passwords
PermitRootLogin no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM no

# Security hardening
X11Forwarding no
AllowTcpForwarding yes
AllowAgentForwarding yes
PermitTunnel no
MaxAuthTries 3
MaxSessions 5
ClientAliveInterval 60
ClientAliveCountMax 3

# Subsystems
Subsystem sftp /usr/lib/openssh/sftp-server

# Allow only the container user
AllowUsers $USER_NAME
EOF

mobile_log "INFO" "SSH configuration written to /etc/ssh/sshd_config"

# Generate host keys if they don't exist
if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
    mobile_log "INFO" "Generating SSH host keys..."
    ssh-keygen -A
    mobile_log "INFO" "SSH host keys generated"
else
    mobile_log "INFO" "SSH host keys already exist"
fi

# Start SSH daemon
mobile_log "INFO" "Starting SSH daemon on port $SSH_PORT..."
/usr/sbin/sshd
if [ $? -eq 0 ]; then
    mobile_log "INFO" "SSH daemon started successfully"
else
    mobile_log "ERROR" "Failed to start SSH daemon"
    exit 1
fi

# Copy tmux configuration to user's home directory
if [ -f /etc/tmux.conf ]; then
    mobile_log "INFO" "Setting up tmux configuration..."
    cp /etc/tmux.conf "$USER_HOME/.tmux.conf"
    chown "$USER_NAME:$USER_NAME" "$USER_HOME/.tmux.conf"
    chmod 644 "$USER_HOME/.tmux.conf"
    mobile_log "INFO" "tmux configuration copied to $USER_HOME/.tmux.conf"
fi

# Set Mosh server port range via environment variable for the user
# This ensures mosh-server knows which ports to use
echo "export MOSH_SERVER_NETWORK_TMOUT=604800" >> "$USER_HOME/.bashrc"
echo "export MOSH_SERVER_SIGNAL_TMOUT=60" >> "$USER_HOME/.bashrc"

mobile_log "INFO" "Mobile access setup complete!"
mobile_log "INFO" ""
mobile_log "INFO" "To connect from your mobile device:"
mobile_log "INFO" "  1. Add your SSH public key to: $SSH_DIR/authorized_keys"
mobile_log "INFO" "  2. Connect via Mosh: mosh --ssh=\"ssh -p $SSH_PORT\" $USER_NAME@<host-ip>"
mobile_log "INFO" "  3. Start tmux session: tmux new -s mobile"
mobile_log "INFO" ""
mobile_log "INFO" "See docs/REMOTE_ACCESS.md for detailed setup instructions."

exit 0
