# wsl_config.ps1
# WSL configuration helper functions (extracted from setup_wizard.ps1)
# These are pure logic functions with no UI dependencies.

# Get total system RAM in GB
function Get-SystemMemoryGB {
    try {
        $totalBytes = (Get-CimInstance -ClassName Win32_ComputerSystem).TotalPhysicalMemory
        $totalMemoryGB = [Math]::Round($totalBytes / 1GB, 1)
        return $totalMemoryGB
    } catch {
        Write-Host "[WARNING] Could not detect system memory: $($_.Exception.Message)" -ForegroundColor Yellow
        return 8  # Default assumption for safety
    }
}

# Get CPU core count
function Get-ProcessorCount {
    try {
        $coreCount = (Get-CimInstance -ClassName Win32_Processor |
            Measure-Object -Property NumberOfLogicalProcessors -Sum).Sum
        if (-not $coreCount) {
            $coreCount = [Environment]::ProcessorCount
        }
        return $coreCount
    } catch {
        Write-Host "[WARNING] Could not detect processor count: $($_.Exception.Message)" -ForegroundColor Yellow
        return 4  # Default assumption
    }
}

# Determine recommended WSL profile based on system resources
function Get-RecommendedWSLProfile {
    param([int]$TotalRAMGB)

    if ($TotalRAMGB -le 10) {
        return 'light'
    } elseif ($TotalRAMGB -le 20) {
        return 'standard'
    } else {
        return 'heavy'
    }
}

# Get profile display name
function Get-ProfileDisplayName {
    param([string]$Profile)

    switch ($Profile) {
        'light' { return 'LIGHT' }
        'standard' { return 'STANDARD' }
        'heavy' { return 'HEAVY' }
        default { return 'STANDARD' }
    }
}

# Map a profile to the processor count it assigns, capped by the real core
# count. Single source of truth for both the .wslconfig `processors` value and
# the container CPU limit (Resolve-ContainerCpuLimit), so the two never drift.
function Get-ProfileProcessors {
    param(
        [string]$Profile,
        [int]$SystemCores = 4
    )

    # Invariant: always assign at least 1 core, even if detection returned 0/negative
    $effectiveCores = [Math]::Max(1, $SystemCores)

    switch ($Profile) {
        'light'    { return [Math]::Min(2, $effectiveCores) }
        'standard' { return [Math]::Min(4, $effectiveCores) }
        'heavy'    { return [Math]::Min(6, $effectiveCores) }
        default    { return 0 }  # Unknown profile
    }
}

# Resolve the container CPU limit (docker-compose `cpus:`) for a chosen setup
# path. The container must never be granted more CPU than the WSL2 VM has, so
# this tracks the profile's processor count. For 'keep' we honour the user's
# existing .wslconfig; for 'skip' WSL uses all host cores, so we do too.
function Resolve-ContainerCpuLimit {
    param(
        [string]$Profile,
        [int]$SystemCores = 4,
        [int]$ExistingProcessors = 0
    )

    $effectiveCores = [Math]::Max(1, $SystemCores)

    switch ($Profile) {
        'keep' {
            if ($ExistingProcessors -gt 0) { return $ExistingProcessors }
            return $effectiveCores
        }
        'skip' { return $effectiveCores }
        default {
            $procs = Get-ProfileProcessors -Profile $Profile -SystemCores $SystemCores
            if ($procs -gt 0) { return $procs }
            # Unknown profile: fall back to the compose floor rather than guess high.
            return [Math]::Min(2, $effectiveCores)
        }
    }
}

# Create .wslconfig file with specified profile settings
function New-WSLConfig {
    param(
        [string]$Profile,
        [string]$Path,
        [int]$SystemCores = 4
    )

    # Profile definitions. Processor count comes from Get-ProfileProcessors so the
    # container CPU limit (Resolve-ContainerCpuLimit) always matches the VM.
    $profiles = @{
        'light'    = @{ Memory = '3GB';  Swap = '2GB' }
        'standard' = @{ Memory = '6GB';  Swap = '4GB' }
        'heavy'    = @{ Memory = '12GB'; Swap = '6GB' }
    }

    $config = $profiles[$Profile]
    if (-not $config) {
        Write-Host "[ERROR] Unknown profile: $Profile" -ForegroundColor Red
        return $false
    }
    $config.Processors = Get-ProfileProcessors -Profile $Profile -SystemCores $SystemCores

    $wslConfigContent = @"
# WSL Configuration - Auto-generated by AI CLI Docker Setup
# Profile: $($Profile.ToUpper())
# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

[wsl2]
# Memory limit for WSL2
memory=$($config.Memory)

# Swap space allocation
swap=$($config.Swap)

# Number of processors to assign
processors=$($config.Processors)

# Disable page reporting for better memory management
pageReporting=false

# Network settings
networkingMode=mirrored
dnsTunneling=true
firewall=true
autoProxy=true
"@

    try {
        # Write config file
        $wslConfigContent | Out-File -FilePath $Path -Encoding UTF8 -Force
        Write-Host "[SUCCESS] WSL configuration saved to: $Path" -ForegroundColor Green
        Write-Host "[INFO] Profile: $($Profile.ToUpper()) - Memory: $($config.Memory), Swap: $($config.Swap), Cores: $($config.Processors)" -ForegroundColor Cyan
        return $true
    } catch {
        Write-Host "[ERROR] Failed to write .wslconfig: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

# Parse existing .wslconfig file and detect if it was created by this wizard
function Parse-WSLConfig {
    param([string]$Path)

    $result = @{
        Exists = $false
        IsOurs = $false
        Memory = $null
        Swap = $null
        Processors = $null
        RawContent = ''
    }

    try {
        $content = Get-Content $Path -Raw -Encoding UTF8 -ErrorAction Stop
    } catch {
        return $result
    }

    $result.Exists = $true
    $result.RawContent = $content

    # Check for our marker comment
    if ($content -match 'Auto-generated by AI CLI Docker Setup') {
        $result.IsOurs = $true
    }

    # Parse values (case-insensitive); stop at whitespace or # to ignore inline comments
    if ($content -match '(?mi)^memory\s*=\s*([^\s#]+)') {
        $result.Memory = $Matches[1].Trim()
    }
    if ($content -match '(?mi)^swap\s*=\s*([^\s#]+)') {
        $result.Swap = $Matches[1].Trim()
    }
    if ($content -match '(?mi)^processors\s*=\s*(\d+)') {
        $result.Processors = [int]$Matches[1]
    }

    return $result
}
