# wsl_config.ps1
# WSL configuration helper functions (extracted from setup_wizard.ps1)
# These are pure logic functions with no UI dependencies.

# Get total system RAM in GB
function Get-SystemMemoryGB {
    try {
        $totalBytes = (Get-CimInstance -ClassName Win32_ComputerSystem).TotalPhysicalMemory
        $totalMemoryGB = [Math]::Round($totalBytes / 1GB, 1)
        return $totalMemoryGB
    } catch {
        Write-Host "[WARNING] Could not detect system memory: $($_.Exception.Message)" -ForegroundColor Yellow
        return 8  # Default assumption for safety
    }
}

# Get CPU core count
function Get-ProcessorCount {
    try {
        $coreCount = (Get-CimInstance -ClassName Win32_Processor |
            Measure-Object -Property NumberOfLogicalProcessors -Sum).Sum
        if (-not $coreCount) {
            $coreCount = [Environment]::ProcessorCount
        }
        return $coreCount
    } catch {
        Write-Host "[WARNING] Could not detect processor count: $($_.Exception.Message)" -ForegroundColor Yellow
        return 4  # Default assumption
    }
}

# Determine recommended WSL profile based on system resources
function Get-RecommendedWSLProfile {
    param([int]$TotalRAMGB)

    if ($TotalRAMGB -le 10) {
        return 'light'
    } elseif ($TotalRAMGB -le 20) {
        return 'standard'
    } else {
        return 'heavy'
    }
}

# Get profile display name
function Get-ProfileDisplayName {
    param([string]$Profile)

    switch ($Profile) {
        'light' { return 'LIGHT' }
        'standard' { return 'STANDARD' }
        'heavy' { return 'HEAVY' }
        default { return 'STANDARD' }
    }
}

# Create .wslconfig file with specified profile settings
function New-WSLConfig {
    param(
        [string]$Profile,
        [string]$Path,
        [int]$SystemCores = 4
    )

    # Profile definitions
    $profiles = @{
        'light' = @{
            Memory = '3GB'
            Swap = '2GB'
            Processors = [Math]::Min(2, $SystemCores)
        }
        'standard' = @{
            Memory = '6GB'
            Swap = '4GB'
            Processors = [Math]::Min(4, $SystemCores)
        }
        'heavy' = @{
            Memory = '12GB'
            Swap = '6GB'
            Processors = [Math]::Min(6, $SystemCores)
        }
    }

    $config = $profiles[$Profile]
    if (-not $config) {
        Write-Host "[ERROR] Unknown profile: $Profile" -ForegroundColor Red
        return $false
    }

    $wslConfigContent = @"
# WSL Configuration - Auto-generated by AI CLI Docker Setup
# Profile: $($Profile.ToUpper())
# Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

[wsl2]
# Memory limit for WSL2
memory=$($config.Memory)

# Swap space allocation
swap=$($config.Swap)

# Number of processors to assign
processors=$($config.Processors)

# Disable page reporting for better memory management
pageReporting=false

# Network settings
networkingMode=mirrored
dnsTunneling=true
firewall=true
autoProxy=true
"@

    try {
        # Write config file
        $wslConfigContent | Out-File -FilePath $Path -Encoding UTF8 -Force
        Write-Host "[SUCCESS] WSL configuration saved to: $Path" -ForegroundColor Green
        Write-Host "[INFO] Profile: $($Profile.ToUpper()) - Memory: $($config.Memory), Swap: $($config.Swap), Cores: $($config.Processors)" -ForegroundColor Cyan
        return $true
    } catch {
        Write-Host "[ERROR] Failed to write .wslconfig: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

# Parse existing .wslconfig file and detect if it was created by this wizard
function Parse-WSLConfig {
    param([string]$Path)

    $result = @{
        Exists = $false
        IsOurs = $false
        Memory = $null
        Swap = $null
        Processors = $null
        RawContent = ''
    }

    try {
        $content = Get-Content $Path -Raw -Encoding UTF8 -ErrorAction Stop
    } catch {
        return $result
    }

    $result.Exists = $true
    $result.RawContent = $content

    # Check for our marker comment
    if ($content -match 'Auto-generated by AI CLI Docker Setup') {
        $result.IsOurs = $true
    }

    # Parse values (case-insensitive); stop at whitespace or # to ignore inline comments
    if ($content -match '(?mi)^memory\s*=\s*([^\s#]+)') {
        $result.Memory = $Matches[1].Trim()
    }
    if ($content -match '(?mi)^swap\s*=\s*([^\s#]+)') {
        $result.Swap = $Matches[1].Trim()
    }
    if ($content -match '(?mi)^processors\s*=\s*(\d+)') {
        $result.Processors = [int]$Matches[1]
    }

    return $result
}
